### ISSUE TITLE
Nuxt 2 inlineRecord not showing

### ISSUE THREAD

**Issue by llanting** [datocms/vue-datocms#87]
I am using the `<datocms-structured-text>` tag to show Structured Text content. However, when I try to show an inlineRecord, it's not working properly. The error I'm seeing is `export 'h' was not found in vue` and `Object(...) is not a function`. I have imported it like this `import { h } from 'vue'`. I suspect the error is due to the fact I'm using Nuxt version 2.15.8 (and Vue 2.6.14). However, I cannot find any examples that use Vue/Nuxt 2 with an inlineRecord. How can I render the inline record?

```
    renderInlineRecord: ({ record }) => {
      switch (record.__typename) {
        case 'LinkRecord':
          return h('a', { href: `/team/${record.slug}` }, record.label)
        default:
          return null;
      }
    }

**Comment by marcelofinamorvieira** [comment]
Hello @llanting can you send us the version of vue-datocms you are using? As this is an error we solved in a more recent version of the package, can you attempt updating it to v4.0.6 and letting us know if the problem persists? Thank you!

**Comment by llanting** [comment]
Hi @marcelofinamorvieira , thank you for your quick reply. I've tried using version `4.0.6` but I keep getting the error `Object(...) is not a function`...

**Comment by marcelofinamorvieira** [comment]
I see @llanting can you send us the version of Node you are using?

**Comment by llanting** [comment]
I was working on Node 16.20.0, but in the meantime we have switched to Node 18. The issue with `export 'h' was not found in vue` has now been resolved. 

I'm seeing that when I do `return h('a', { attrs: { href: node.url } }, children);` it always adds the baseUrl of the project to the given `href`. Am I correct in assuming that the package replaces the `a` with a `NuxtLink`? Is there any way to prevent this?

**Comment by llanting** [comment]
Correction, I see that the URLS were added incorrectly. When we add the urls with `http:` add the start, they are recognized as external urls and working perfectly.

To summarize: my original issue was fixed by using Node >18 instead of 16. Thanks for your help!
